pipeline:
  build-base-image:
    when:
      event: [push, tag]
    image: plugins/docker
    repo: registry.usw.co/cloud/amazon-ssm-agent-base
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
  build-base-image-tagged:
    when:
      event: tag
      branch: mainline
    image: plugins/docker
    repo: registry.usw.co/cloud/amazon-ssm-agent-base
    tags:
      - ${DRONE_TAG}
      - latest
  build:
    when:
      event: [push, tag]
    image: registry.usw.co/cloud/amazon-ssm-agent-base
    commands:
      - make build-linux
      - echo "${DRONE_TAG}" > latest.txt
  publish-versioned:
    when:
      event: tag
    image: plugins/s3
    acl: public-read
    region: "eu-west-1"
    bucket: "uswitch-tools"
    strip_prefix: bin/
    source: bin/**/*
    target: amazon-ssm-agent/${DRONE_TAG}
  publish-latest:
    when:
      event: tag
    image: plugins/s3
    acl: public-read
    region: "eu-west-1"
    bucket: "uswitch-tools"
    strip_prefix: bin/
    source: bin/**/*
    target: amazon-ssm-agent/latest
  publish-latest-txt:
    when:
      event: tag
    image: plugins/s3
    acl: public-read
    region: "eu-west-1"
    bucket: "uswitch-tools"
    source: latest.txt
    target: amazon-ssm-agent/
