pipeline:
  build-base-image:
    image: plugins/docker
    when:
      event: push
    repo: registry.usw.co/cloud/amazon-ssm-agent-base
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
  build:
    image: registry.usw.co/cloud/amazon-ssm-agent-base
    environment:
      - GO111MODULE=on
    commands:
      - make build-linux
