pipeline:
  build-base-image:
    image: plugins/docker
    repo: registry.usw.co/cloud/amazon-ssm-agent-base
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
  build:
    image: registry.usw.co/cloud/amazon-ssm-agent-base
    commands:
      - ls
      - pwd
      - echo $HOME 
      - make build-linux
